In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/fake_job_postings.csv')
df.sample(2)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
16878,16879,Marketing and Sales Representative- Full Time ...,"US, TX, Carrollton",NaN,NaN,"LEI Home Enhancements, is an Ohio based compan...",LEI Home Enhancements is now hiring for entry ...,Responsibilities in this program include: Sale...,Our Company Offers:Outstanding Growth Opportun...,0,1,1,NaN,NaN,NaN,NaN,Sales,0
16836,16837,Warehouse Helper,"US, UT, North Salt Lake",NaN,0-0,NaN,Several positions available.Duties include but...,Eligibility:- Must pass drug test- Must be at ...,NaN,0,0,0,Full-time,Not Applicable,Unspecified,Food Production,Manufacturing,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  str
 2   location             17534 non-null  str
 3   department           6333 non-null   str
 4   salary_range         2868 non-null   str
 5   company_profile      14572 non-null  str
 6   description          17879 non-null  str
 7   requirements         15184 non-null  str
 8   benefits             10668 non-null  str
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  str
 13  required_experience  10830 non-null  str
 14  required_education   9775 non-null   str
 15  industry             12977 non-null  str
 16  function             11425 non-null  str
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), str(13)
memory usage: 49.6 MB

In [5]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [6]:
(df.isnull().sum()/len(df))*100

job_id                  0.000000
title                   0.000000
location                1.935123
department             64.580537
salary_range           83.959732
company_profile        18.501119
description             0.005593
requirements           15.078300
benefits               40.335570
telecommuting           0.000000
has_company_logo        0.000000
has_questions           0.000000
employment_type        19.412752
required_experience    39.429530
required_education     45.329978
industry               27.421700
function               36.101790
fraudulent              0.000000
dtype: float64

In [7]:
df.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='str')

In [8]:
df.drop(columns=["job_id","department","salary_range"], inplace=True)

In [9]:
df.columns

Index(['title', 'location', 'company_profile', 'description', 'requirements',
       'benefits', 'telecommuting', 'has_company_logo', 'has_questions',
       'employment_type', 'required_experience', 'required_education',
       'industry', 'function', 'fraudulent'],
      dtype='str')

In [10]:
categorical_features = df.select_dtypes(include='object').columns
numerical_features = df.select_dtypes(include='number').columns

C:\Users\Akhilesh\AppData\Local\Temp\ipykernel_17616\3445889894.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(include='object').columns

In [11]:
[[categorical_features,
numerical_features]]

[[Index(['title', 'location', 'company_profile', 'description', 'requirements',
         'benefits', 'employment_type', 'required_experience',
         'required_education', 'industry', 'function'],
        dtype='str'),
  Index(['telecommuting', 'has_company_logo', 'has_questions', 'fraudulent'], dtype='str')]]

In [12]:
TEXT_COLUMNS = [
    "title",
    "company_profile",
    "description",
    "requirements",
    "benefits"
]

for col in TEXT_COLUMNS:
    df[col] = df[col].fillna("")

In [13]:
CATEGORICAL_COLUMNS = [
    "location",
    "employment_type",
    "required_experience",
    "required_education",
    "industry",
    "function"
]

for col in CATEGORICAL_COLUMNS:
    df[col] = df[col].fillna("Unknown")

In [14]:
df.isnull().sum()

title                  0
location               0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
dtype: int64

In [ ]:
# Remove duplicate rows

print("Before:", len(df))

df = df.drop_duplicates().reset_index(drop=True)

print("After:", len(df))

Before: 17880
After: 17590

In [ ]:
# Remove leading/trailing spaces

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

C:\Users\Akhilesh\AppData\Local\Temp\ipykernel_17616\1126013313.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [ ]:
# Replace multiple spaces
# like : Data     Scientist     ----> Data Scientist

import re

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].apply(
        lambda x: re.sub(r"\s+", " ", x) if isinstance(x, str) else x
    )

C:\Users\Akhilesh\AppData\Local\Temp\ipykernel_17616\2225852418.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [ ]:
# Remove HTML tags
from bs4 import BeautifulSoup

def remove_html(text):
    if isinstance(text, str):
        return BeautifulSoup(text, "html.parser").get_text()
    return text

for col in TEXT_COLUMNS:
    df[col] = df[col].apply(remove_html)

In [ ]:
# Remove URLs
import re

def remove_urls(text):
    if isinstance(text, str):
        return re.sub(r"http\S+|www\S+", "", text)
    return text

for col in TEXT_COLUMNS:
    df[col] = df[col].apply(remove_urls)

In [ ]:
# Remove email addresses
def remove_email(text):
    if isinstance(text, str):
        return re.sub(r'\S+@\S+', '', text)
    return text

for col in TEXT_COLUMNS:
    df[col] = df[col].apply(remove_email)

In [21]:
# Remove strange Unicode characters

def clean_unicode(text):
    if isinstance(text, str):
        return text.encode("ascii", "ignore").decode()
    return text

for col in TEXT_COLUMNS:
    df[col] = df[col].apply(clean_unicode)

In [22]:
df["text"] = (
    "Title: " + df["title"] +
    " Company Profile: " + df["company_profile"] +
    " Description: " + df["description"] +
    " Requirements: " + df["requirements"] +
    " Benefits: " + df["benefits"] +
    " Industry: " + df["industry"] +
    " Function: " + df["function"] +
    " Employment Type: " + df["employment_type"] +
    " Experience: " + df["required_experience"] +
    " Education: " + df["required_education"] +
    " Location: " + df["location"]
)

In [23]:
df.sample(2)

,title,location,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,text
13153,Visual Designer,"US, CA, Palo Alto",Declara is focused on bringing data to life. O...,The Senior Visual Designer is responsible for ...,Someone who wants to influence your own develo...,,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Art/Creative,0,Title: Visual Designer Company Profile: Declar...
9570,Event Producer (Corporate and Private),"GR, , Athens",Optimal Business Action was created in 2005 in...,"On behalf of our client, a European strategic ...",Required Qualifications:- Event Management Exp...,,0,1,0,Full-time,Mid-Senior level,Master's Degree,Marketing and Advertising,Public Relations,0,Title: Event Producer (Corporate and Private) ...

In [24]:
df.to_csv(
    "fake_job_cleaned.csv",
    index=False
)